name: igdesign
channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  - python==3.11.9
  - ipython
  - pip
  - pytorch>=2.0,<2.1
  - cuda-version = 12.4
  - cuda-nvcc
  - pandas>=2.0,<2.1
  - lightning>=2.0,<2.1
  - cytoolz>=0.12.3
  - einops>=0.8.0
  - hydra-core>=1.3.2
  - biopython>=1.84
  - datasets>=2.20.0
  - hmmer=3.3.2
  - huggingface_hub>=0.24.5
  - transformers>=4.42.4
  - anarci
  - pip:
    - torchtyping>=0.1.4
