structure_path: "./examples/1n8z.pdb"
lmdesign_checkpoint: "./ckpts/igdesign_acvr2b_holdout.ckpt"
pmpnn_checkpoint: "./ckpts/igmpnn_acvr2b_holdout.ckpt"
save_path: "./output/1n8z_results.csv"

region_order: ["hcdr1", "hcdr2", "hcdr3", "lcdr1", "lcdr2", "lcdr3"] # CDRs to design and order to design in

lmdesign_num_decoding_orders: 10
lmdesign_num_pmpnn_seqs: 10
lmdesign_num_lm_seqs: 10
lmdesign_pmpnn_logit_temperature: 0.5
lmdesign_output_logit_temperature: 0.5

independent_loss: true

condition_on_light_chain: false
condition_on_antigen: true
predict_light_chain: true
batch_size: 1
num_batches: 1
random_seed: 0

epitope_idxs_or_all: all # either a list of idxs or "all"

antigen_chain_id: "C"
heavy_chain_id: "B"
light_chain_id: "A"

regions:
  hcdr1:
    positions: [25, 26, 27, 28, 29, 30, 31, 32]
    chain: "heavy"
    
  hcdr2:
    positions:  [50, 51, 52, 53, 54, 55, 56, 57]
    chain: "heavy"

  hcdr3:
    positions: [96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108]
    chain: "heavy"

  lcdr1:
    positions: [26, 27, 28, 29, 30, 31]
    chain: "light"

  lcdr2:
    positions: [49, 50, 51]
    chain: "light"

  lcdr3:
    positions: [88, 89, 90, 91, 92, 93, 94, 95, 96]
    chain: "light"
